# Generated by Django 4.2.1 on 2024-02-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0002_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='lastname',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='patients',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='Patienthistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='anamnesis.patients')),
            ],
        ),
    ]
