# Generated by Django 4.2.1 on 2024-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0003_patients_lastname_alter_patients_name_patienthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
