# Generated by Django 4.2.1 on 2024-02-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0004_patients_address_patients_city_patients_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
    ]
