# Generated by Django 4.2.1 on 2024-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0006_patient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='prescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='visit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
