# Generated by Django 4.2.1 on 2024-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0007_patienthistory_diagnostic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='history',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='visit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
