# Generated by Django 4.2.1 on 2024-03-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0010_patient_doctor_alter_patienthistory_nextappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='nextappointment',
            field=models.DateTimeField(null=True),
        ),
    ]
