# Generated by Django 4.1.5 on 2024-03-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0012_alter_patienthistory_nextappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='familyBackground',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='personalBackground',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
