# Generated by Django 4.1.5 on 2024-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0013_patienthistory_familybackground_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='familyBackground',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='personalBackground',
        ),
        migrations.AddField(
            model_name='patient',
            name='familyBackground',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='personalBackground',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
