# Generated by Django 4.1.5 on 2024-03-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0014_remove_patienthistory_familybackground_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='history',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='prescription',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='visit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
