# Generated by Django 4.1.5 on 2024-03-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0015_alter_patienthistory_diagnostic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='familyBackground',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='personalBackground',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
