# Generated by Django 4.1.5 on 2024-03-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0016_alter_patient_familybackground_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='physicalExam',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
