# Generated by Django 4.2.1 on 2024-03-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0018_image_patienthistory_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientImage', to='anamnesis.patienthistory'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='images',
            field=models.ManyToManyField(related_name='patientHistories', to='anamnesis.image'),
        ),
    ]
