# Generated by Django 4.2.1 on 2024-04-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0024_remove_patienthistory_images_patientimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientimage',
            name='image',
        ),
        migrations.AddField(
            model_name='patientimage',
            name='image',
            field=models.ManyToManyField(to='anamnesis.image'),
        ),
    ]
