# Generated by Django 4.2.1 on 2024-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0026_alter_patientimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
